version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ssant/hexlet-devops-lvl1
    command: ["npm", "test"]
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: