version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ssant/hexlet-devops-lvl1
    environment:
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_PORT
    command: ["bash", "-c", "sleep 3s && npm test"]
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
