version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ssant/hexlet-devops-lvl1
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-hexlet}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-hexlet}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_HOST: ${DATABASE_DB:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
    command: ["bash", "-c", "sleep 5s && npm test"]
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-hexlet}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
