version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ssant/hexlet-devops-lvl1
    command: npm test
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: