version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ssant/hexlet-devops-lvl1
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
    command: ["npm", "test"]
#    command: ["bash", "-c", "sleep 3s && npm test"]
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
